### ISSUE TITLE
💡 [REQUEST] - Optional output format structure

### ISSUE THREAD

**Issue by blaisebits** [dreadnode/robopages-cli#22]
### Implementation PR

N/A

I was trying to write this myself, but I really suck at Rust. 

### Reference Issues

N/A

### Summary

It could be really cool if you could add optional output formatting information to the YAML definition for use with something like Pydantic for creating structure outputs.

### Basic Example

Example for Nmap output

```
    outputs:
      ip_address:
        type: string
        description: The host IP address
      ports:
        type: List[string]
        description: The port number
      states:
        type: List[string]
        description: Define if the port is open, closed, or filtered
      services:
        type: List[string]
        description: The service running on the associated port
      versions:
        type: List[string]
        description: The version of the server software running
      scripts:
        type: List[List[string]]
        description: Nmap Scripting engine output
```

### Drawbacks

None I can think of

### Unresolved questions

The example shows a means of defining it for python, I'm unsure how this variables would translate to other languages.
